# Name of the deployed worker
name = "propaganda-worker"

# Entry point for the worker
main = "src/index.ts"

# Cloudflare Workers runtime version
compatibility_date = "2024-05-14"

# List of KV namespaces the worker can access
kv_namespaces = [
    { binding = "SCHEDULE_KV", id = "7f755e834d164bce9defba151adc4534" },
    { binding = "SYSTEM_META_KV", id = "2b4a9fa91ff7419aba1b436524b98a6b" },
    { binding = "GROUP_KV", id = "012e34e26082417baa0ce36a359adaab" },
    { binding = "GROUP_MEMBERS_KV", id = "88340834c1674a68bb8e1e033d600783" },
    { binding = "CONVERSATION_KV", id = "eaaea009fb2e474fab299f29775330eb" },
    { binding = "MESSAGE_KV", id = "5b6df97263dd4f839aba77a566fcb72e" },
    { binding = "AI_USER_KV", id = "f1e0146544f3467c8ab050308eca6eb8" },
    { binding = "AUDIT_LOG_KV", id = "2bf52912e89047c6874fbe90ef5f47b2" },
]

[triggers]
# Run the `scheduled` handler once every minute

crons = ["*/1 * * * *"]
